#!/usr/bin/env bash

##
## Usage: fin compile

# Abort if anything fails
set -e

#-------------------------- Helper functions --------------------------------

# Console colors
red='\033[0;31m'
green='\033[0;32m'
green_bg='\033[1;97;42m'
yellow='\033[1;33m'
NC='\033[0m'
DOCROOT_PATH="${PROJECT_ROOT}/${DOCROOT}"
echo-red () { echo -e "${red}$1${NC}"; }
echo-green () { echo -e "${green}$1${NC}"; }
echo-green-bg () { echo -e "${green_bg}$1${NC}"; }
echo-yellow () { echo -e "${yellow}$1${NC}"; }

#-------------------------- Execution --------------------------------
# Stack initialization
echo -e "${green_bg} Step 1 ${NC}${green} YARN BUILD ${NC}"
cd ${PROJECT_ROOT}/${DOCROOT}/themes/custom/decode

yarn build-all

echo -e "${green_bg} Component library ${NC}${yellow} ${PROJECT_URL}/component-library ${NC}"
